In [6]:
import torch
import torch_geometric.transforms as T
from torch_geometric.data import Data

In [61]:
# pos = torch.tensor([[0],
#                     [0],
#                     [0],
#                     [0.1],
#                     [0.2],
#                     [0.3],
#                     [2],
#                     [2],
#                     [2.1],
#                     [2.2]])
pos = torch.tensor([[0],
                    [0],
                    [0],
                    [0.1],
                    [0.2],
                    [0.3],
                    [0.4],
                    [0.5],
                    [0.6],
                    [2.2]])
x = torch.rand((10,1))
y = torch.rand((10,1))

data = Data(x=x,edge_index=None,edge_attr=None,y=y,pos=pos)
data

Data(pos=[10, 1], x=[10, 1], y=[10, 1])

In [69]:
graph = T.KNNGraph(k=6,loop=True,force_undirected=True)(data)
graph

Data(edge_index=[2, 74], pos=[10, 1], x=[10, 1], y=[10, 1])

In [70]:
graph.edge_index[:,:]

tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6,
         6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9,
         9, 9],
        [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5,
         6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3,
         4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7,
         8, 9]])

In [68]:
data.adj_t = None
graph = T.ToUndirected()(graph)
graph.edge_index

tensor([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6,
         6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9,
         9, 9],
        [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5,
         6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3,
         4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7,
         8, 9]])

In [65]:
graph = T.AddSelfLoops()(graph)
graph.edge_index

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3,
         3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8,
         8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
         1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4,
         5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 3, 4, 5, 6, 7, 8, 9, 0,
         3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9]])